### ISSUE TITLE
How to generate vocab.txt

### ISSUE THREAD

**Issue by nanoponge** [dhl123/Airtag-2023#1]
How is the vocab.txt in training_data generated? Can you provide us with the code?

**Comment by dhl123** [comment]
It is already provided in "[create_vocab_atlas.py](https://github.com/dhl123/Airtag-2023/blob/main/create_vocab_atlas.py)"

**Comment by bxybx** [comment]
Please forgive me for asking a silly question. In your source code, if each Python file needs to be run individually, what is the order of execution for these files?
![屏幕截图 2024-07-29 171709](https://github.com/user-attachments/assets/995d00bc-9f95-4cd7-b73a-b8672a1e094c)
